version: "2"

linters:
  # start with a solid baseline; change to "standard" if this is too strict
  default: fast
  enable:
    - staticcheck
    - govet
    - ineffassign
    - errcheck
    - revive
    - gocritic
    - unused

formatters:
  enable:
    - gofmt
    - goimports
    # - gci        # enable if you use gci
    # - gofumpt    # enable if you prefer gofumpt

issues:
  max-same-issues: 0
  exclude-use-default: false
  exclusions:
    rules:
      - path: _test\.go
        linters: [errcheck]

run:
  # v2 has no default timeout; keep using CLI flag or set here if desired
  concurrency: 0